[package]
name = "Dragon-shell"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "0.7"
reedline = "0.13"
chrono = "0.4"
prettytable = "0.10"
toml = "0.7"
serde = { version = "1.0", features = ["derive"] }

[env]
key = "MY_VAR"
value = "value_here"
